### ISSUE TITLE
Control font size of the rendered pdf

### ISSUE THREAD

**Issue by drfurtado** [DamonCharlesRoberts/fancy-doc#1]
Great extension!
Is there a way to control the font size of the rendered pdf? Or even better, control the font size of specific document parts, e.g., a table?

**Comment by DamonCharlesRoberts** [comment]
Thanks!


If you want to see what the default settings are and change them for the files using this extension, you can do so by looking at [this file](https://github.com/DamonCharlesRoberts/fancy-doc/blob/main/_extensions/fancy-doc/_extension.yml) which defines the extension's default theme settings. Any nested option under "pdf" is totally customizable.

That file is what allows for the shortcut of:

```
format:
  fancy-doc-pdf: default
```

You can change the font. You'd remove "default" and replace it with the "fontsize" option in your yaml like below:

```
format:
  fancy-doc-pdf:
    fontsize: 20pt
```

In terms of a document-level control over content types, I am not aware of any way to do that with Quarto. You could control the font for each table. But how to do so, entirely depends on how the table is being generated (e.g., Markdown, in R, Python, HTML, LaTeX code blocks, etc.). You'd want to look at the documentation for the tool you're using to do that. 

Let me know if I can clarify or address follow-up Q's.

**Comment by drfurtado** [comment]
Thank you so much!!!
